extended code to allow L > 1 for sampling z in the decoder as defined…
y0ast/Variational-Autoencoder pull request #10
Opened 2017-05-09 22:43 UTC by JohannesHeidecke

… in the paper.

The paper does state that L=1 is usually sufficient, if the batch size is large enough, but with this change it is free to the user to select L.

2017-05-10 15:29 UTC, y0ast requested changes
Looks good, could you address the minor things?

2017-05-10 15:29 UTC, y0ast commented on VAE.py
> +                      0.5 * ((x - reconstructed_x)**2 / T.exp(log_sigma_decoder))).sum(axis=2).sum(axis=0) / self.L
can you turn this into a .mean(axis=0)? avoids the explicit division

2017-05-10 15:29 UTC, y0ast commented on VAE.py
> +            logpxz = - T.nnet.binary_crossentropy(reconstructed_x, x).sum(axis=2).sum(axis=0) / self.L
See above

2017-05-12 10:55 UTC, JohannesHeidecke commented on VAE.py
> +            logpxz = - T.nnet.binary_crossentropy(reconstructed_x, x).sum(axis=2).sum(axis=0) / self.L
good point, updated the code!

2017-05-14 12:13 UTC, y0ast commented
There are now two dots between the sum and the mean?

2017-05-15 21:05 UTC, JohannesHeidecke commented
yup, my bad. fixed it.

2017-05-16 13:53 UTC, y0ast commented
Thanks, I'll run some checks in the weekend to verify that it works

2017-05-23 21:43 UTC, y0ast approved these changes

2017-05-23 21:43 UTC, y0ast commented
Works well, thanks!

2017-05-23 21:43 UTC, merged

2017-05-28 15:08 UTC, JohannesHeidecke commented
🎉